### ISSUE TITLE
Filtering deliverd shows section with no content

### ISSUE THREAD

**Issue by reharmsen** [peternijssen/lovelace-postnl#14]
@peternijssen with the new release #11 has been solved/implemented 
Unfortunately I do see a 'bug' with this.

When there are past delivery's within the defined past_days... it is working as expected:
![afbeelding](https://user-images.githubusercontent.com/22921691/57752983-22845200-76eb-11e9-88dd-71a0143ee106.png)

when I changed past_days to (for instance 1) the header and table is still shown, without data.
I would expect the whole Delivery section to disappear:
![afbeelding](https://user-images.githubusercontent.com/22921691/57753089-6c6d3800-76eb-11e9-830e-fda7962504a4.png)

Relevant configuration:
```yaml
- type: 'custom:postnl-card' 
  delivery: sensor.postnl_delivery
  date_format: DD-MM-YYYY
  time_format: 'HH:mm'
  past_days: 1
  hide:
    delivered: false
    first_letter: true
    header: true
```

Would it be possible to change/fix this?
